# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Package

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
          version: 1.5.1

    - name: Install Dependencies
      run: poetry install -v

    - name: Build and publish
      shell: bash
      run: |
        poetry publish --build --username '__token__'  --password ${{ secrets.PYPI_API_TOKEN }}
